main = "src/index.ts"
compatibility_date = "2023-08-21"

[observability]
enabled = true

[env.dev]
vars = { ALLOWED_DOMAINS = "*" }

name = "elpatodraw-worker-dev"

routes = [
  { pattern = "fileworker-dev.elpato.dev", custom_domain = true }
]

r2_buckets = [
  { binding = "elpatodraw", bucket_name = "elpatodraw-dev" }
]

[env.production]
vars = { ALLOWED_DOMAINS = "https://elpatodraw.com" }

name = "elpatodraw-worker"

routes = [
  { pattern = "fileworker.elpato.dev", custom_domain = true }
]

r2_buckets = [
  { binding = "elpatodraw", bucket_name = "elpatodraw" }
]